### ISSUE TITLE
Token exires.

### ISSUE THREAD

**Issue by martennienhuis** [StefanNienhuis/homebridge-bold#1]
Hi Stefan. 

Today my token is expired. Can you please fix this?

Thanks a lot.

Marten

**Comment by StefanNienhuis** [comment]
I'm looking into it right now.

**Comment by StefanNienhuis** [comment]
This issue has been fixed with version [v1.0.4](https://github.com/StefanNienhuis/homebridge-bold/releases/tag/v1.0.4).
