### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by Gnol86** [StefanNienhuis/homebridge-bold#10]
Hello,

Thanks for your job.
The plugin does not work. I have this message in the logs:

`[Bold] Error (ERR_TLS_CERT_ALTNAME_INVALID) while refreshing token: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: api.sesamtechnology.com. is not in the cert's altnames: DNS:*.boldsmartlock.com`

Can you help me ?

**Comment by jamespreedy** [comment]
Same for me - please let me know if there is any additional information I can provide that might help fix this. 👍🏻

**Comment by StefanNienhuis** [comment]
Hi there, 

This should be fixed in v2.1.4. Let me know if you run into any issues.

**Comment by jamespreedy** [comment]
2.1.4 fixed it for me @StefanNienhuis - thanks for your help. 👍🏻

**Comment by Gnol86** [comment]
Fixed ! Thanks you !
