### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by skle** [StefanNienhuis/homebridge-bold#11]
Is it possible to share Bold API documentation? I would like to implement this in a PHP project and it's pretty difficult for me to extract flow and API calls (including parameters) from this typescript project.

Thanks in advance!

**Comment by StefanNienhuis** [comment]
Hi there, the API docs are available from Bold at: https://apidoc.boldsmartlock.com/

You will need a client id and secret though. You can take them from the Bold app by inspecting the network traffic while logging in.
