### ISSUE TITLE
Lock not visible anymore

### ISSUE THREAD

**Issue by tomdh76** [StefanNienhuis/homebridge-bold#14]
This plugin worked fine, but lately my locks are not loaded? Is it because the api is down or other problems it that area? Maybe this https://github.com/lwestenberg/bold_smart_lock/issues/8 is a similar issue?

**Comment by tomdh76** [comment]
And now one day later the locks suddenly reappear.
In the logs:

7:23:31 PM] [Bold] Found 2 new devices supporting remote activation.
[11/3/2022, 7:23:31 PM] [Bold] Configuring accessory with device name 'Voordeur'
[11/3/2022, 7:23:31 PM] [Bold] Configuring accessory with device name 'Achterdeur'

**Comment by StefanNienhuis** [comment]
Hi there, unless there was something in the logs saying something is wrong, it is likely an issue on Bold's side. I'm glad it's resolved.
