### ISSUE TITLE
Authentication website: Failed to fetch

### ISSUE THREAD

**Issue by dreasvandonselaar** [StefanNienhuis/homebridge-bold#17]
The authentication website (https://stefannienhuis.github.io/homebridge-bold/) returns "Failed to fetch" for any (Bold registered) phone number I try. Is it broken?

**Comment by jamespreedy** [comment]
Same here sadly. I'm getting a load of authentication / token errors in HomeBridge and I wanted to refresh the token.

**Comment by StefanNienhuis** [comment]
The authentication website was still using the old api url. This has now been updated.

**Comment by jamespreedy** [comment]
@StefanNienhuis - thanks for your quick help here, much appreciated. 🍺

When going through authentication, I not get a "Load failed" error after entering my password.
Phone, validation SMS are all fine, and I'm able to log into the app with no issue using these credentials.
Am I doing something silly?

Thanks again. 🎄

**Comment by StefanNienhuis** [comment]
Glad I’m able to help. What error are you getting now?

**Comment by jamespreedy** [comment]
![Screenshot 2022-12-11 at 1 53 52 pm](https://user-images.githubusercontent.com/559531/206907756-1a2f1692-7b7e-4123-a54d-6b8ad0f191da.jpg)

I just get this after entering my password.

**Comment by StefanNienhuis** [comment]
Could you open the web inspector and see the console for errors?

**Comment by jamespreedy** [comment]
![Screenshot 2022-12-11 at 1 56 15 pm](https://user-images.githubusercontent.com/559531/206907869-ea4c06a5-6a7e-409f-9a92-332bcf38f0c8.jpg)

**Comment by StefanNienhuis** [comment]
It seems Bold has removed support for Legacy authentication... the new configuration flow is currently only implemented for the Config UI. Are you able to use the homebridge-config-ui-x plugin for configuration?

**Comment by jamespreedy** [comment]
Yep, trying it now. Thank you again. 😀

**Comment by minuscorp** [comment]
I'm still getting errors trying to get the tokens:

![image](https://user-images.githubusercontent.com/3819883/211359476-d34d541e-65b0-484e-b90f-b6c2ac61154a.png)

**Comment by minuscorp** [comment]
Still not working so nothing to do with the API being down for a time

**Comment by StefanNienhuis** [comment]
Hi, sorry for the delay. Legacy authentication doesn't work anymore since Bold changed their authentication strategy on their servers. For now authentication can only be done through the Config UI.

**Comment by minuscorp** [comment]
There's no config ui in the latest release, just a token and secret to be fulfilled, how do I get them?

**Comment by StefanNienhuis** [comment]
Are you using HOOBS? HOOBS has their own flavour of config ui that doesn't work with the standard homebridge config ui.

**Comment by minuscorp** [comment]
for some reason deleting the old config and reinstalling the plugin worked /shrug
