### ISSUE TITLE
Error: getaddrinfo ENOTFOUND bold.nienhuisdevelopment.com

### ISSUE THREAD

**Issue by Designator-Ol** [StefanNienhuis/homebridge-bold#18]
As of today I'm getting the following errors trying to refresh the tokens on two different hosts:

- `[Bold] Error (undefined) while refreshing token: Error: getaddrinfo ENOTFOUND bold.nienhuisdevelopment.com`
- `[BoldBLE] request to https://bold.nienhuisdevelopment.com/oauth/refresh failed, reason: getaddrinfo ENOTFOUND bold.nienhuisdevelopment.com`

As a result I'm not able to use the lock with homekit anymore. The bold app is still functional.

Could you please look into it.
Much appreciated!
Greetz Desi

**Comment by StefanNienhuis** [comment]
Hi there,

There was a DNS issue, which should be resolved now. It may take some time for the DNS cache to clear, so you might need to wait a little.

Best regards,
Stefan

**Comment by Designator-Ol** [comment]
The issue seems to be resolved. Thanks for the quick response !
Have a nice evening !
