### ISSUE TITLE
3 van de 4 sloten werken

### ISSUE THREAD

**Issue by michaelzetter** [StefanNienhuis/homebridge-bold#19]
Wanneer ik in de woning app op mijn voordeurslot klik (Deze verdwijt ook soms uit de woning) rijg ik een laad icoontje te zien, verder gebeurt er niks.
MIjn overige 3 sloten werken wel.

Wanneer ik in homebridge kijk zie ik:
[5/12/2023, 10:11:57 PM] [Bold] Error (BLECommunicationError) while activating device (20977): Unknown error
[5/12/2023, 10:11:57 PM] [Bold] Error (BLECommunicationError) while activating device (20977): Unknown error

Via de bold app reageert het slot wel.

Hopelijk kun je me verder helpen, alvast bedankt.

**Comment by StefanNienhuis** [comment]
Dit lijkt een error vanuit Bold te zijn. In dit geval zou de Bold Connect moeite hebben met het slot bereiken. Wanneer je Bluetooth uitschakelt op je telefoon (of ver weg van de sloten bent), is het dan wel mogelijk om dit slot te openen? Als dit niet zo is, zou de Bold connect dichter bij het slot moeten staan.
