### ISSUE TITLE
Amazing plugin, just one but

### ISSUE THREAD

**Issue by bgoncal** [StefanNienhuis/homebridge-bold#2]
The plugin is very nice and I was looking for one like this for a while, but its response is very slow, to unlock the door it can take several seconds, I imagine that there is a challenge in the communication between the homebridge and Bold "API" though, so Im just opening this issue to report this and maybe look for improvements in the code.

**Comment by StefanNienhuis** [comment]
Hi there, thanks for using the plugin.

I’ve also noticed that it’s a bit slow, but there’s not much to be done about it. I ran some timing tests a while back and the two things that took a considerable amount of time are the HomeKit to plugin connection and the plugin to Bold API. Neither of these can be sped up on my end.

It’s also a fact that the Bold connect isn’t too fast (at least on my end). You can try it out by turning your bluetooth off and using the Bold app to see how long it takes directly (via Bold connect) in comparison to the plugin. If it’s a significant difference I’ll look into what might be causing it.
