### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by brnl** [StefanNienhuis/homebridge-bold#23]
Just a minor inconvenience: In the README.md under [Manual Configuration](https://github.com/StefanNienhuis/homebridge-bold/blob/master/README.md#manual-configuration), the hyperlink to the [config.example.json](https://github.com/StefanNienhuis/homebridge-bold/blob/master/config.example.json) is broken. It should be https://github.com/StefanNienhuis/homebridge-bold/blob/master/plugin/config.example.json

Off-topic: By the way, I tried your referral and it says the 10% discount will be calculated but that doesn't show on checkout. I have contacted support for that.

**Comment by StefanNienhuis** [comment]
Fixed. Thanks for letting me know.

That's strange. I've never used a referral code myself so I'm not quite sure what the process is.

**Comment by brnl** [comment]
> That's strange. I've never used a referral code myself so I'm not quite sure what the process is.
Their reply:

> Helaas is op dit moment het niet mogelijk om de referral code te gebruiken, door onze huidige kerstactie. Aangezien helaas geen kortingscodes gecombineerd kunnen worden in onze webshop.
