### ISSUE TITLE
Bluetooth communication

### ISSUE THREAD

**Issue by bgoncal** [StefanNienhuis/homebridge-bold#3]
Would be possible somehow that the lock is unlocked via bluetooth (like when you don't have the bridge)? I believe this would make it faster and also more reliable for those who live in apartments and have to drop connection when getting inside the lift and then facing a situation where they leave the lift, there is still not 100% 4G available and the home wifi at the door is trying to connect.

**Comment by StefanNienhuis** [comment]
Although I do believe that it’s possible, it would require reverse engineering the Bluetooth communication, for which I don’t have the knowledge or time to do it.

Unless anyone else is willing to do this and open a PR, I’ll be closing this issue.
