### ISSUE TITLE
Error while activating - token expired

### ISSUE THREAD

**Issue by StefanNienhuis** [StefanNienhuis/homebridge-bold#5]
Since version 2.1.0 there seems to be an issue with activating devices due to an expired access token. I'm looking to this right now.

**Comment by StefanNienhuis** [comment]
The Bold API seems to report an invalid expiration time. I have contacted Bold about this. For now, legacy authentication will need to be used.

**Comment by Djkriz** [comment]
Thanks for the info!

**Comment by StefanNienhuis** [comment]
I seem to have figured out the issue. It was not a Bold issue. Expect an update within the hour.

**Comment by StefanNienhuis** [comment]
Resolved in v2.1.1

**Comment by Djkriz** [comment]
Thanks! Working!
