### ISSUE TITLE
Update authorization link to auth.boldsmartlock.com

### ISSUE THREAD

**Issue by dreasvandonselaar** [StefanNienhuis/homebridge-bold#6]
When linking the plugin to Bold, a URL can be copied: 
`https://boldsmartlock.com/app/authorize?response_type=code&client_id=HomeBridge&redirect_uri=https://bold.nienhuisdevelopment.com/oauth/callback&state=*****
`
It returns a 404, Bold changed the URL to auth.boldsmartlock.com:
`https://auth.boldsmartlock.com/app/authorize?response_type=code&client_id=HomeBridge&redirect_uri=https://bold.nienhuisdevelopment.com/oauth/callback&state=*****`

The new URL works with the latest Bold Android app.

**Comment by StefanNienhuis** [comment]
Hi there, sorry for the delay. I've contacted Bold to check if this is correct.

**Comment by StefanNienhuis** [comment]
Bold said that this page is not yet in production. I also asked them why android doesn’t work on the current one (I can’t verify that though).

**Comment by dreasvandonselaar** [comment]
You can verify the 404 from any browser though? That said, I just tried again and the old (404) link now suddenly does seem to trigger a Bold app link action. I did upgrade to the Bold beta Android release earlier today (waiting for Google home integration which shows up already but doesn't seem to work yet), so both links may work in beta (but no longer in stable?).

It's definitely a 404 though, so Bold should confirm a link that does provide a proper HTTP response :)

**Comment by StefanNienhuis** [comment]
It's the same on iOS: the page is a 404, but it provides a button to open the Bold app in Safari's top bar.

Bold said it will probably be a few weeks before the new log in page will go into production, so for now I'll close this issue.

**Comment by StefanNienhuis** [comment]
The beta version v2.1.2-beta1 includes the new authorization url for beta users. I opened #7 as a notice.
