### ISSUE TITLE
Host the backend on a NAS

### ISSUE THREAD

**Issue by Neo33ASM** [StefanNienhuis/homebridge-bold#8]
Hi,

Is it possible to host the backend on a Synology NAS ?

Regards,

Julien

**Comment by Neo33ASM** [comment]
I already have homebridge hosted on my NAS, I’m talking about your token refresh backend

**Comment by StefanNienhuis** [comment]
The source code for the backend is provided, albeit in the form of Serverless functions. You could adopt this to Node, but you’d still require a client id and secret from Bold.
