### ISSUE TITLE
Platform homekit_controller does not generate unique IDs

### ISSUE THREAD

**Issue by machielw** [StefanNienhuis/homebridge-bold#9]
Thanks for your work! 
I integrated homebridge with Home assistant. 
in homebridge It is working fine. All locks available. And working. 
In Home assistant I have this logbook entry. And only one lock out of 3 availible. 
something with the plug-in? Thanks

Logger: homeassistant.components.lock
Source: helpers/entity_platform.py:620 
Integration: Slot (documentation, issues) 
First occurred: 14:27:32 (2 occurrences) 
Last logged: 14:27:32

Platform homekit_controller does not generate unique IDs. ID homekit-Unknown-8 already exists - ignoring lock.voordeur

**Comment by StefanNienhuis** [comment]
It seems that Bold no longer provides the serial number of the device to the plugin, so it was falling back to the string 'Unknown'. The homekit_controller integration was using this serial to construct device ids, so they would be duplicated.

Version 2.1.3-beta1 should address this by generating a serial number based un the unique device id. Could you try this out?

**Comment by machielw** [comment]
👍
Perfect
thanks !!!
